Update readme for 2023.1
stackhpc/a-universe-from-nothing pull request #172
Opened 2024-08-29 14:10 UTC by Alex-Welsh

2024-09-04 13:32 UTC, markgoddard requested changes

2024-09-04 13:32 UTC, markgoddard commented on README.rst
> +   git clone https://opendev.org/openstack/kayobe.git -b stable/2023.1
We shouldn't change this.

2024-09-04 13:32 UTC, markgoddard commented on README.rst
> +   git clone https://github.com/stackhpc/a-universe-from-nothing.git kayobe-config -b stable/2023.1
We shouldn't change this.

2024-09-04 13:32 UTC, markgoddard commented on README.rst
> -    64df77adc709   192.168.33.5:4000/openstack.kolla/opensearch:2024.1-rocky-9                  "dumb-init --single-…"   6 hours ago   Up 6 hours (healthy)             opensearch
We shouldn't change these.

2024-09-04 13:32 UTC, markgoddard commented on README.rst
> +    pip install python-barbicanclient -c https://releases.openstack.org/constraints/upper/2023.1
We shouldn't change this.

2024-09-04 15:19 UTC, Alex-Welsh commented on README.rst
> +   git clone https://opendev.org/openstack/kayobe.git -b stable/2023.1
Reverted

2024-09-04 15:19 UTC, Alex-Welsh commented on README.rst
> +   git clone https://github.com/stackhpc/a-universe-from-nothing.git kayobe-config -b stable/2023.1
Reverted

2024-09-04 15:19 UTC, Alex-Welsh commented on README.rst
> -    64df77adc709   192.168.33.5:4000/openstack.kolla/opensearch:2024.1-rocky-9                  "dumb-init --single-…"   6 hours ago   Up 6 hours (healthy)             opensearch
Reverted

2024-09-04 15:19 UTC, Alex-Welsh commented on README.rst
> +    pip install python-barbicanclient -c https://releases.openstack.org/constraints/upper/2023.1
Reverted

2024-09-05 08:16 UTC, markgoddard approved these changes

2024-09-05 08:16 UTC, merged